### ISSUE TITLE
Overflow text at Home

### ISSUE THREAD

**Issue by lnsf** [Frandre01000/Group8#1]
![Screen Shot 2020-02-11 at 18 36 42](https://user-images.githubusercontent.com/38149771/74225247-a8c2d880-4cfd-11ea-91b0-c53f2c1416fa.png)

もしかして：仕様

**Comment by makotia** [comment]
モバイル対応まだってREADME.mdに書かれてるしレスポンシブ全体的にまだなのでは？

**Comment by Frandre01000** [comment]
まだです（血涙）
ここラズパイ女に指摘されたら学生生活終わるナリ...

**Comment by lnsf** [comment]
ファイトﾅﾘ
